version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-go-lambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1b0rpp4kbz6ml"
s3_prefix = "sam-go-lambda"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
