version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.16

  pre_build:
    commands:
      - echo "go version"
      - go version
      - echo "go get aws lambda library"
      - go get github.com/aws/aws-lambda-go/lambda

  build:
    commands:
      - echo "go build"
      - GOOS=linux go build -o main lambda.go

  post_build:
    commands:
      - echo "create zip"
      - zip main.zip main config.yaml

artifacts:
  files:
    - main.zip
