name: lambda-build-deploy

on:
  push:
    branches: [lambda]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          go-version: "1.16.7"

      - name: go get aws lambda library
        run: go get github.com/aws/aws-lambda-go/lambda

      - name: go build
        run: GOOS=linux go build lambda.go

      - name: create zip
        run: zip main.zip main config.yaml

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: deploy test
        run: echo "deploy test"
