name: lambda-build-deploy

on:
  push:
    branches: [lambda]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          go-version: "1.16.7"

      - name: go get aws lambda library
        run: go get github.com/aws/aws-lambda-go/lambda

      - name: go build
        run: GOOS=linux go build -o main lambda.go

      - name: create zip
        run: zip main.zip main config.yaml

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: upload main.zip to s3
        run: aws s3 cp main.zip s3://go-lambda-deploy

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: update Lambda function
        run: |
          aws lambda update-function-code --function-name go-lambda --s3-bucket go-lambda-deploy --s3-key main.zip\
          | jq '.FunctionName, .LastUpdateStatus'
