name: go-run

on:
  workflow_dispatch:

jobs:
  go-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          go-version: '1.16.7'
      - run: go version
        

      - name: Go Run
        run: go run .
