name: lambda-build-deploy-with-aws-sam

on:
  push:
    branches: [sam]

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # - name: Setup Go environment
      #   uses: actions/setup-go@v2.1.3
      #   with:
      #     go-version: "1.16.7"

      - name: Setup AWS SAM
        uses: aws-actions/setup-sam@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Sam build
        run: sam build --use-container

      - name: Add config.yaml into build artifact
        run: cp config.yaml .aws-sam/build/SamGoLambdaFunction/config.yaml

      - name: Upload artifacts to artifact buckets
        run: |
          sam package \
            --s3-bucket aws-sam-cli-managed-default-samclisourcebucket-1b0rpp4kbz6ml \
            --output-template-file packaged-template.yaml

      - uses: actions/upload-artifact@v2
        with:
          name: packaged-template.yaml
          path: packaged-template.yaml
  
  deploy-prod:
    needs: [build-and-package]
    runs-on: ubuntu-latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Sam deploy
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
